server:
  #端口
  port: 8082
spring:
  #邮箱配置
  mail:
    #右键服务器地址
    host: smtp.163.com
    #协议
    protocol: smtp
    #编码格式
    default-encoding: utf-8
    #授权码
    password: YXVFNVWSLJANCPYM
    #邮箱地址
    username: wanglufei0411@163.com
    #端口
    port: 25

  #rabbitmq配置
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    virtual-host: /
    port: 5672
    #开启手动确认
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    timeout: 10000ms
    host: localhost
    port: 6379
    database: 1 # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024 # 最大连接数，默认 8
        max-wait: 10000ms # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200 # 最大空闲连接，默认 8
        min-idle: 5

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    check-template-location: true
